default_stages: [ commit ]
default_install_hook_types: [ pre-commit, pre-push ]
repos:
  - repo: local
    hooks:

      - id: version-check
        name: Check if version(s) are in sync
        always_run: true
        language: system
        pass_filenames: false
        entry: poetry run nox -s fix_version
      - id: shellcheck
        name: Lint shell scripts
        language: system
        types: [ shell ]
        entry: shellcheck -x
      - id: update_setup_py
        name: Update setup.py
        language: system
        pass_filenames: false
        always_run: true
        entry: githooks/update_setup_py.sh
      - id: prohibit_push_to_main
        name: prohibit push to main
        language: system
        pass_filenames: false
        always_run: true
        stages: [ push ]
        entry: githooks/prohibit_push_to_main.sh

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: [ '--py38-plus' ]
        types: [ python ]
        exclude: "setup.py"
