name: Check setup.py

on: pull_request

jobs:
  check_setup_py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install via setup.py
        run: python3 setup.py install