name: Check if versions are consistent

on: pull_request

jobs:
  check-version-numbers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.1.13

      - name: Install Python Dependencies
        run: poetry install

      - name: Run pre-commit
        run: pre-commit run
