name: Check pre-commit

on:
  pull_request:
  workflow_call:


jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.2.1

      - name: Install Python Dependencies
        run: poetry install

      - name: Run pre-commit
        run: poetry run pre-commit run

      - name: Show changes on working copy
        run: git status --porcelain=v1 -uno
      - name: Show diff on working copy
        run: git diff --cached
      - name: Check if pre-commit changed any files
        run: |
          [ -z "$(git status --porcelain=v1 -uno 2>/dev/null)" ]
