name: Run pytest tests

on:
  push:
    branches-ignore:
      - github-pages/*

jobs:
  integration_tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install sqlite
        run: apt-get install sqlite3

      - uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.1.11

      - name: Poetry install
        run: poetry install

      - name: Poetry build
        run: poetry build

      - name: Poetry run pytest integration tests
        run: poetry run pytest tests
