name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: 'Upload URL'
        required: true

jobs:
  check-release:
    uses: ./.github/workflows/check_precommit.yaml

  integration_tests:
    uses: ./.github/workflows/pytest.yaml

  release-documentation:
    needs: [integration_tests, check-release]
    uses: ./.github/workflows/create_release_docu.yaml

  upload:
    needs: [release-documentation]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.6
      with:
        poetry-version: 1.4.0

    - name: Poetry install
      run: poetry install

    - name: Release
      run: poetry run nox -s release
      env:
        POETRY_PYPI_TOKEN_PYPI: "${{ secrets.PYPI_TOKEN }}"